
```{r setup, include=FALSE}
setwd("<INSERT WORKING DIRECTORY>")
root = getwd()
knitr::opts_chunk$set(root = root)
knitr::opts_knit$set(root = root)
```

Load libraries
```{r}
library(data.table)
```

With CERES files
```{r}
ccle = fread(paste0(root, "/CCLE_expression.csv"))
ceres = fread(paste0(root, "/CRISPR_gene_effect.csv"))
model = fread(paste0(root, "/sample_info.csv"))
ceres <- ceres[, .SD, .SDcols = c(1, grep("CDS2",colnames(ceres)))]
ccle <- ccle[, .SD, .SDcols = c(1, grep("CDS1",colnames(ccle)))]
model <- model[, .SD, .SDcols = c(1, grep("primary_disease",colnames(model)))]
colnames(ccle) <- c("ID","CDS1")
colnames(ceres) <- c("ID","CDS2")
colnames(model) <- c("ID","type")
merged <- merge(ccle, ceres, by = "ID", all = TRUE)
merged <- merge(merged, model, by = "ID", all = TRUE)
complete <- merged[!is.na(CDS1) & !is.na(CDS2)]
rm(ccle, model, merged, ceres)
complete$CDS1 <- (2^complete$CDS1 - 1)+0.0625
complete <- complete[order(complete$CDS1), ]
fwrite(data.table(log2(complete$CDS1)),"results_CDS1hist_cer.csv")
IC50 <- 1.273
result_IC50_cer <- data.table(
  below_IC50_percentage = sum(complete$CDS1 < IC50) / nrow(complete) * 100,
  above_IC50_percentage = sum(complete$CDS1 > IC50) / nrow(complete) * 100,
  below_IC50_count = sum(complete$CDS1 < IC50),
  above_IC50_count = sum(complete$CDS1 > IC50)
)
fwrite(result_IC50_cer,"result_IC50_cer.csv")
rm(IC50,result_IC50_cer)
complete$CDS1 <- ave(complete$CDS1, cut(complete$CDS1, breaks = quantile(complete$CDS1, probs = seq(0, 1, by = 0.1), na.rm = TRUE), include.lowest = TRUE), FUN = mean)
complete <- complete[, .SD, .SDcols = c(2, 3)]
results <- complete[, .(
  Mean = mean(CDS2, na.rm = TRUE),
  N = .N,
  UP = quantile(CDS2, 0.75, na.rm = TRUE),
  LOW = quantile(CDS2, 0.25, na.rm = TRUE)
), by = .(Bin = CDS1)]
results <- results[order(Bin)]
results <- na.omit(results)
colnames(results) <- c("Mean_CDS1","mean_CDS2","N_decile","UP_decile","LOW_decile")
fwrite(results,"results_cer.csv")
rm(complete,results)
```

```{r}
sessionInfo()
```

