
```{r setup, include=FALSE}
root = "<INSERT WORKING DIRECTORY>"
knitr::opts_chunk$set(root = root)
knitr::opts_knit$set(root = root)
```

Load libraries
```{r}
library(data.table)
```

Read in necessary files
```{r}
ranking = fread("unprocessed_data.txt")
essentials = fread("essentials.txt")
```

Prepare data for use
```{r}
cell_lines = c("K562", "NCIH2030", "LPS141", "SKMEL2", "MCF7")

test = melt(ranking[, colnames(ranking)[grep(cell_lines[1], colnames(ranking))], with = F], id.vars = cell_lines[1])
setnames(test, cell_lines[1], "gene")
test[, c("var", "cell_line") := tstrsplit(variable, "_", fixed=TRUE)]
test[, variable := NULL]

for (i in 2:length(cell_lines)) {
  cur = melt(ranking[, colnames(ranking)[grep(cell_lines[i], colnames(ranking))], with = F], id.vars = cell_lines[i])
  setnames(cur, cell_lines[i], "gene")
  cur[, c("var", "cell_line") := tstrsplit(variable, "_", fixed=TRUE)]
  cur[, variable := NULL]
  
  test = rbind(test, cur)
}

test = test[complete.cases(test)]
```

Identify essential genes
```{r}
test[, essential := ifelse(gene %in% essentials$Essentials, 1, 0)]
test[, nonessential := ifelse(gene %in% essentials[`Non-essentials` != "", `Non-essentials`], 1, 0)]
```

Get cumulative ranking of essential and non-essential genes using a rolling window, then calculate the ROC-AUC using a version of a Riemann sum
```{r}
test[, essential_cumsum := cumsum(essential), by = cell_line]
test[, essential_cumpercentage := (essential_cumsum / max(essential_cumsum))*100, by = cell_line]
test[, nonessential_cumsum := cumsum(nonessential), by = cell_line]
test[, nonessential_cumpercentage := (nonessential_cumsum / max(nonessential_cumsum))*100, by = cell_line]

test[, roc_auc := 
           (shift(essential_cumpercentage, 1, type = "lead") - essential_cumpercentage) * ((shift(nonessential_cumpercentage, 1, type = "lead") + nonessential_cumpercentage ) / 2), by = cell_line]

fwrite(test[, 100 - (sum(roc_auc, na.rm = T) / 100), by = cell_line], "roc_values.txt")
```
