
```{r setup, include=FALSE}
root = "<INSERT WORKING DIRECTORY>"
knitr::opts_chunk$set(root = root)
knitr::opts_knit$set(root = root)
```

Load libraries
```{r}
library(data.table)
library(survival)
library(survminer)
library(stringr)
```

Read in necessary files
```{r}
tcga.expr = fread(paste0(root, "/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"))
tcga.survival = fread(paste0(root, "/TCGA-CDR-SupplementalTableS1.txt"))
```

Prepare and clean up data
```{r}
cds1_expr = as.data.table(t(tcga.expr[grep("^CDS1",tcga.expr$gene_id),]), 
                          keep.rownames = "id")
setnames(cds1_expr, "V1", "expr")
cds1_expr = cds1_expr[-1,]
cds1_expr[, expr := as.numeric(expr)]

# extract sample type code so we can select out the normals
cds1_expr[, stc_number := str_extract(id, "(?<=TCGA-[A-Z0-9]{2}-[A-Z0-9]{4}-)[0-9]{2}")]
cds1_expr[, stc_whole := str_extract(id, "(?<=TCGA-[A-Z0-9]{2}-[A-Z0-9]{4}-)[0-9A-Z]{3}")]

# how many patients have more than 1 sample?
cds1_expr[, patient := str_extract(id, "(?<=TCGA-[A-Z0-9]{2}-)[A-Z0-9]+")]
nrow(cds1_expr[, .N, by = patient][N>1])
# number of unique patients
unique_pt = length(cds1_expr[, unique(patient)])

# keep only the first ones, as these are the primary tumors
# if a patient only has metastatic samples we use those
cds1_expr.keep = cds1_expr[cds1_expr[order(id), .I[1], by = patient]$V1]
# make sure you're not losing patients
identical(unique_pt, nrow(cds1_expr.keep))

tcga.survival[, patient := str_extract(bcr_patient_barcode, "(?<=TCGA-[A-Z0-9]{2}-)[A-Z0-9]{4}")]
```

Plot overall survival by CDS1 expression
```{r}
plotting = merge(cds1_expr.keep[stc_number!=11,], tcga.survival[, .(patient, OS, OS.time)], by = "patient") # exclude 11 codes, which are normals
plotting = plotting[complete.cases(plotting),]

bottom = quantile(plotting$expr)[2]
top = quantile(plotting$expr)[4]

lowq = floor(nrow(plotting)*0.25)
topq = ceiling(nrow(plotting)*0.75)
bottom = plotting[order(expr)][lowq, expr]
top = plotting[order(expr)][topq, expr]

plotting[, quant := ifelse(expr <= bottom, "bottom",
                           ifelse(expr >= top, "top", "exclude"))]
plotting = plotting[quant != "exclude"]

fit = survfit(Surv(OS.time, OS) ~ quant, data = plotting)

ggsurvplot(fit)

summary(coxph(Surv(OS.time, OS) ~ quant, data = plotting))

surv_diff <- survdiff(Surv(OS.time, OS) ~ quant, data = plotting)
summary(surv_diff)
```


